import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/layout/Navbar";
import { Theme } from '@radix-ui/themes';
import { SessionProvider } from 'next-auth/react'; // Import SessionProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-l-bg">

          <Theme>
            <Navbar />
            <div className="m-5 p-5">
              <SessionProvider>
                {children}
              </SessionProvider>
            </div>
          </Theme>
      </body>
    </html>
  );
}
